import Head from "next/head";
import Board from "@/components/Board";
import DraggableItemList from "@/components/DraggableItemList";

import usePositionStore from "@/store/usePositionStore";
import { Flex } from "@chakra-ui/react";

export default function Home() {
  const position = usePositionStore((state) => state.position);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex direction="row" justify="space-around" align="center">
          <Board position={position} />
          <DraggableItemList />
        </Flex>
      </main>
    </>
  );
}
