import Head from "next/head";
import Board from "@/components/Board";

import usePositionStore from "@/store/usePositionStore";

export default function Home() {
  const position = usePositionStore((state) => state.position);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Board position={position} />
      </main>
    </>
  );
}
