import Head from "next/head";

import { Stage } from "@pixi/react";
import DraggableSprite from "@/components/DraggableSprite";

import { Flex } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex direction="row" justify="space-around" align="center">
          <Stage options={{ backgroundColor: 0x1099bb }}>
            <DraggableSprite />
          </Stage>
        </Flex>
      </main>
    </>
  );
}
