import Head from "next/head";

import { Stage } from "@pixi/react";
import DraggableSprites from "@/components/DraggableSprites";
import ListOfSprites from "@/components/ListOfSprites";

import { Flex, Heading } from "@chakra-ui/react";
import { ConnectButton } from "@rainbow-me/rainbowkit";

export default function Home() {
  return (
    <>
      <Head>
        <title>Plants and Pillars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex margin="3% 0" justify="space-evenly">
          <Heading>
            Plants and Pillars
          </Heading>
          <ConnectButton />
        </Flex>
        <Flex direction="row" justify="space-around" align="center">
          <Stage options={{ backgroundColor: "#e0d9c9" }}>
            <DraggableSprites />
          </Stage>
          <ListOfSprites />
        </Flex>
      </main>
    </>
  );
}
